spring:
  profiles:
    active: default
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    #url: jdbc:h2:mem:test;MODE=MYSQL
    url: jdbc:h2:~/customerdb;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver